title: "404: Still here"
author: Betx
url: "https://beto98.github.io"
baseurl: ""

description: >
  signal received, meaning pending âœ¦

permalink: /:slug/

favicon: "./logo.png"

twitter:
  username: ""
  card: summary_large_image

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "home.."
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true

  show_projects: true
  show_blog: true
  show_post: true
  show_post: true
  show_old_projects: true
  show_misc_list: false
  show_reading_time: true
  show_tags: true

  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

soopr:
  publish_token: ""

highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
